version: '3.9'
networks:
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.5.0.0/16

volumes:
  pgadmin:
  storage:
  product:


services:
  postgresstorage:
    container_name: postgres_storage_container
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./data/storage:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres    
  
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: "admin1234"
      POSTGRES_DB: "StorageDB"
      POSTGRES_USER: "admin"

  postgresproduct:
    container_name: postgres_product_container
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./data/product:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres    
  
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: "admin1234"
      POSTGRES_DB: "ProductDB"
      POSTGRES_USER: "admin"


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - postgres
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DEFAULT_EMAIL: "admin@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "admin1234"
  